@Api = http://localhost:5277
@FinanceAndAccounting = {{Api}}/FinanceAndAccounting
@AccountsReceivable = {{FinanceAndAccounting}}/AccountsReceivable

GET {{AccountsReceivable}}/GetAccountEndpoint/
Accept: application/json


###

POST {{AccountsReceivable}}/AddAccount/
Content-Type: application/json
Expect: 200

{
  "Name": "To"
}

###

GET {{AccountsReceivable}}/GetAccountEndpoint/{{accountId}}
Accept: application/json

###

GET {{AccountsReceivable}}/GetAccou
Accept: application/json
